USE tienda;

 SELECT nombre FROM producto;
 SELECT nombre, precio FROM producto;
 SELECT * FROM producto;
 SELECT nombre, precio AS euros,(precio *1.08) AS USD FROM producto; SELECT nombre AS "product name", precio AS euros,(precio *1.08) AS USD FROM producto;
 SELECT UPPER(nombre) AS nombre_mayus, precio FROM producto;
 SELECT LOWER(nombre) AS nombre_minus, precio FROM producto;
 SELECT nombre, UPPER(LEFT(nombre, 2)) AS iniciales FROM fabricante;
 SELECT nombre, ROUND(precio) AS rounded_price FROM producto;
 SELECT nombre, TRUNCATE(precio, 0) AS truncated_price FROM producto;
 SELECT codigo_fabricante FROM producto;
 SELECT DISTINCT codigo_fabricante FROM producto;
 SELECT nombre FROM fabricante ORDER BY nombre ASC;
 SELECT nombre FROM fabricante ORDER BY nombre DESC;
 SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
 SELECT * FROM fabricante LIMIT 5;
 SELECT * FROM fabricante LIMIT 3,2;
 SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
 SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
 SELECT nombre, precio FROM producto WHERE codigo_fabricante =2;
 SELECT p.nombre AS producto, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante= f.codigo;
 SELECT p.nombre AS producto, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC;
 SELECT p.codigo AS codigo_producto, p.nombre AS producto, f.codigo AS codigo_fabricante, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante= f.codigo;
 SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio ASC LIMIT 1;
 SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio DESC LIMIT 1;
 SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre ='Lenovo';
 SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre= 'Crucial' AND p.precio > 200;
 SELECT p.nombre AS producto, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate' ;
 SELECT p.nombre AS producto, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN( 'Asus', 'Hewlett-Packard','Seagate');
 SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e'; 
 SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w';
 SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
 SELECT DISTINCT f.nombre, f.codigo FROM fabricante f JOIN producto p ON p.codigo_fabricante= f.codigo;
 SELECT f.nombre AS fabricante, p.nombre AS producto, p.precio FROM fabricante f LEFT JOIN producto p ON f.codigo= p.codigo_fabricante;
 SELECT f.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.codigo IS NULL;
 SELECT nombre, precio FROM producto WHERE codigo_fabricante =( SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'); 
 SELECT * FROM producto WHERE precio >=(SELECT MAX(precio) FROM producto WHERE codigo_fabricante= (SELECT codigo FROM fabricante WHERE nombre= 'Lenovo'));
 SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') ORDER BY precio DESC LIMIT 1;
 SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard') ORDER BY precio ASC LIMIT 1;
 SELECT * FROM producto WHERE precio >=( SELECT MAX(precio) FROM producto WHERE codigo_fabricante= (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
 SELECT nombre,precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus') AND precio > (SELECT AVG(precio) FROM producto p WHERE codigo_fabricante =(SELECT codigo FROM producto WHERE nombre = 'Asus'));

USE universidad;

SELECT apellido1, apellido2, nombre FROM persona WHERE tipo= 'alumno' ORDER BY apellido1, apellido2, nombre;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo= 'alumno' AND telefono IS NULL;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = 'alumno' AND YEAR(fecha_nacimiento) = 1999;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo= 'profesor' AND telefono IS NULL AND nif LIKE '%k';
SELECT nombre FROM asignatura WHERE cuatrimestre =1 AND curso= 1 AND id_grado= 7;
SELECT p.apellido1, p.apellido2, p.nombre, d.nombre AS departamento FROM profesor pr JOIN persona p ON pr.id_profesor= p.id JOIN departamento d ON pr.id_departamento= d.id ORDER BY p.apellido1, p.apellido2, p.nombre;
SELECT a.nombre, ce.anyo_inicio, ce.anyo_fin FROM alumno_se_matricula_asignatura am JOIN persona p ON am.id_alumno= p.id JOIN asignatura a ON am.id_asignatura= a.id JOIN curso_escolar ce ON am.id_curso_escolar= ce.id WHERE p.nif = '26902806M';
SELECT DISTINCT d.nombre FROM departamento d JOIN profesor pr ON d.id= pr.id_departamento JOIN asignatura a ON pr.id_profesor= a.id_profesor JOIN grado g ON a.id_grado= g.id WHERE g.grado = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT nombre, apellido1, apellido2 FROM alumno_se_matricula_asignatura am JOIN persona p ON am.id_alumno= p.id JOIN curso_escolar ce ON am.id_curso_escolar= ce.id WHERE p.tipo= 'alumno' AND ce.anyo_inicio = 2018 AND ce.anyo_fin= 2019;
SELECT d.nombre AS departamento, p.apellido1, p.apellido2, p.nombre FROM profesor pr LEFT JOIN departamento d ON pr.id_departamento= d.id JOIN persona p ON pr.id_profesor= p.id ORDER BY d.nombre, p.apellido1, p.apellido2, p.nombre;
SELECT apellido1, apellido2, nombre FROM profesor pr LEFT JOIN departamento d ON pr.id_departamento= d.id JOIN persona p ON pr.id_profesor= p.id WHERE d.id IS NULL;
SELECT d.nombre FROM departamento d LEFT JOIN profesor pr ON d.id= pr.id_departamento WHERE pr.id_profesor IS NULL;
SELECT p.apellido1, p.apellido2, p.nombre FROM profesor pr LEFT JOIN asignatura a ON p.id_profesor= a.id_profesor JOIN persona p ON pr.id_profesor= p.id WHERE a.id_asignatura IS NULL;
SELECT a.nombre FROM asignatura a LEFT JOIN profesor pr ON a.id_asignatura= pr.id_profesor WHERE pr.id_profesor IS NULL;
SELECT d.nombre FROM departamento d LEFT JOIN profesor pr ON d.id= pr.id_departamneto LEFT JOIN asignatura a ON pr.id_profesor= a.id_profesor WHERE a.id_asignatura IS NULL;
SELECT COUNT(*) AS total_alumnes FROM persona WHERE tipo= 'alumno';
SELECT COUNT(*) AS alumnes_1999 FROM persona WHERE tipo= 'alumno' AND YEAR(fecha_nacimiento)= 1999;
SELECT d.nombre AS departamento, COUNT(pr.id_profesor) AS num_profesores FROM departamento d JOIN profesor pr ON d.id= pr.id_departamento GROUP BY d.nombre ORDER BY num_profesores DESC;
SELECT d.nombre AS departamento, COUNT(pr.id_profesor) AS num_profesores FROM departamento d LEFT JOIN profesor pr ON d.id = pr.id_departamento GROUP BY d.nombre ORDER BY num_profesores DESC;
SELECT g.nombre AS grado, COUNT(a.id_asignatura) AS num_asignaturas FROM grado g LEFT JOIN asignatura a ON g.id_grado = a.id_grado GROUP BY g.nombre ORDER BY num_asignaturas DESC;
